### ISSUE TITLE
Use Docker

### ISSUE THREAD

**Issue by dagapp** [dagapp/goald#40]
For better scaling and easier deployment, it should be considered to use Docker

**Comment by ZuxiGIT** [comment]
Check my new PR: https://github.com/dagapp/goald/pull/42

**Comment by uf00led** [comment]
Make another docker container for the frontend service. Commands for deploy (from the folder `goald-frontend`). In this sequence:
```
npm i
npm run build
npm run srv
```

**Comment by uf00led** [comment]
Make another docker container for the frontend service. Commands for deploy (from the folder `goald-frontend`). In this sequence:
```
npm i
npm run build
npm run srv
```

**Comment by ZuxiGIT** [comment]
Check out my new PR: https://github.com/dagapp/goald/pull/45
